Update Existing Django Application Exercise/greetings/urls.py
from django.urls import path
from . import views

app_name = 'greetings' # allows using 'greetings:index' for url and reverse_lazy methods
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('fancy/<int:pk>', views.FancyView.as_view(), name='fancy'),
]

Update Existing Django Application Exercise/greetings/models.py
from django.db import models

class Greeting(models.Model):
    message = models.CharField(max_length=200)

Update Existing Django Application Exercise/greetings/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Greeting

class IndexView(generic.ListView):
    template_name = 'greetings/index.html'
    context_object_name = 'greeting_list'

    def get_queryset(self):
        """Return the all greetings."""
        return Greeting.objects.all()

class CreateView(generic.edit.CreateView):
    template_name = 'greetings/create.html'
    model = Greeting
    fields = ['message']
    success_url = reverse_lazy('greetings:index') # more robust than hardcoding to /greetings/; directs user to index view after creating a greeting

class UpdateView(generic.edit.UpdateView):
    template_name = 'greetings/update.html'
    model = Greeting
    fields = ['message']
    success_url = reverse_lazy('greetings:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'greetings/delete.html' # override default of greetings/greeting_confirm_delete.html
    model = Greeting
    success_url = reverse_lazy('greetings:index')

class FancyView(generic.DetailView):
    template_name = 'greetings/fancy.html' # convert greeting
    model = Greeting
    

Update Existing Django Application Exercise/greetings/templates/greetings/create.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

Update Existing Django Application Exercise/greetings/templates/greetings/fancy.html
{% load staticfiles %}    
<head>  
  <link rel="stylesheet" href="{%  static  'css/style.css'  %}">
</head>

<body>
  <p id="fancy" class="font-italic">{{ object.message }}</p>
  <a href="{% url 'greetings:index' %}">Return to Greetings</a>
</body>

Update Existing Django Application Exercise/greetings/templates/greetings/index.html
{% load staticfiles %}    
<head>  
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{%  static  'css/style.css'  %}">
</head>

<body>
{% if greeting_list %}
    <ul>
    {% for greeting in greeting_list %}
        <li>
          {{ greeting.message }}
          <span><a href="{% url 'greetings:update' greeting.id %}">edit</a></span>
          <span><a href="{% url 'greetings:delete' greeting.id %}">delete</a></span>
          <span><a href="{% url 'greetings:fancy' greeting.id %}">fancy</a></span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No greetings are available.</p>
{% endif %}
<a href="{% url 'greetings:create' %}">Create a New Greeting</a>
</body>