Deploy Django Exercise/list/urls.py
from django.urls import path

from . import views

app_name = 'lists'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('<int:pk>/done', views.DoneView, name='done'),
]

Deploy Django Exercise/list/models.py
from django.db import models

class listItem(models.Model):
  isDone = models.BooleanField(default=False)
  item = models.CharField(max_length=200)
    
  def __str__(self):
    return self.item

Deploy Django Exercise/list/forms.py
from django import forms
from .models import listItem

class doneForm(forms.Form):
  isDone = forms.BooleanField(required=False)

  class Meta:
    model = listItem
    exclude = ['item']

Deploy Django Exercise/list/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import listItem
from .forms import doneForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

class IndexView(generic.ListView):
    template_name = 'list/index.html'
    context_object_name = 'list'

    def get_queryset(self):
        """Return the all items in list."""
        return listItem.objects.all()

class CreateView(generic.edit.CreateView):
  template_name = 'list/create.html'
  model = listItem
  fields = ['item']
  success_url = reverse_lazy( 'lists:index')

class UpdateView(generic.edit.UpdateView):
    template_name =  'list/update.html'
    model = listItem
    fields = ['item']
    success_url = reverse_lazy( 'lists:index')

class DeleteView(generic.edit.DeleteView):
    template_name =  'list/delete.html' # override default of listItems listItem_confirm_delete.html
    model = listItem
    success_url = reverse_lazy( 'lists:index')

def DoneView(request, pk):
  list_item = get_object_or_404(listItem, pk=pk)
  form = doneForm(request.POST or None)

  if request.method == 'POST':
    if form.is_valid():
      if request.POST.get('done'):
        list_item.isDone = True
        list_item.save()
      else:
        list_item.isDone = False
        list_item.save()

  return HttpResponseRedirect(reverse_lazy('lists:index'))

Deploy Django Exercise/list/templates/list/create.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

Deploy Django Exercise/list/templates/list/delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object.item }}"?</p>
  <input type="submit" value="Confirm">
</form>

Deploy Django Exercise/list/templates/list/index.html
{% if list %}
    <ul>
    {% for thing in list %}
        <li>
          <form action="{% url 'lists:done' thing.id %}" method="post">{% csrf_token %}
            {% if thing.isDone %}
             <input type="checkbox" name="done" value="Update" checked>
            {% else %}
             <input type="checkbox" name="done" value="Update">
            {% endif %}
            <input type="submit" value="Submit">
          {{ thing.item }}          
          <span><a href="{% url 'lists:update' thing.id %}">edit</a></span>
          <span><a href="{% url 'lists:delete' thing.id %}">delete</a></span>
        </form>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No items in list</p>
{% endif %}
<a href="{% url 'lists:create' %}">Add item to list</a>

Deploy Django Exercise/list/templates/list/update.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
  <a href="{% url 'lists:delete' listitem.id %}">delete</a>
</form>