Django Girls/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    #url(r'^signup/$', views.signup_view, name="signup"),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

Django Girls/greetings/urls.py
from django.urls import path
from . import views

app_name = 'greetings' # allows using 'greetings:index' for url and reverse_lazy methods
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.CreateView.as_view(), name='create'),
    path('examples/', views.ExamplesView.as_view(), name='examples'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

Django Girls/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('greetings/', include('greetings.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

Django Girls/accounts/models.py
from django.db import models

# Create your models here.

Django Girls/greetings/models.py
from django.db import models

class Greeting(models.Model):
    message = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.message

Django Girls/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        #Django will take the new form to validate
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Save to database:
            user = form.save()
            # LATER Log the user in
            login(request, user)
            return redirect('greetings:index')
    else:
        # The request method is GET so create a fresh form
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # LATER Log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('greetings:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('greetings:index')

Django Girls/greetings/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Greeting
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class IndexView(generic.ListView):
    template_name = 'greetings/index.html'
    context_object_name = 'greeting_list'

    def get_queryset(self):
        """Return the all greetings."""
        return Greeting.objects.all()


#@login_required(login_url="/accounts/login/")
@method_decorator(login_required, name='dispatch')
class CreateView(generic.edit.CreateView):
    template_name = 'greetings/create.html'
    model = Greeting
    fields = ['message']
    success_url = reverse_lazy('greetings:index') # more robust than hardcoding to /greetings/; directs user to index view after creating a greeting

class ExamplesView(generic.ListView):
    template_name = 'greetings/examples.html'
    model = Greeting
    fields = ['message']
    success_url = reverse_lazy('greetings:index')

class UpdateView(generic.edit.UpdateView):
    template_name = 'greetings/update.html'
    model = Greeting
    fields = ['message']
    success_url = reverse_lazy('greetings:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'greetings/delete.html' # override default of greetings/greeting_confirm_delete.html
    model = Greeting
    success_url = reverse_lazy('greetings:index')

Django Girls/accounts/templates/accounts/login.html
<h1>Log in</h1>
<form class="site-form" action="{% url 'accounts:login'%}" method="post">
    {% csrf_token%}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value={{ request.GET.next }}>
    {% endif %}
    <input type = "submit" value="Login">
</form>

Django Girls/accounts/templates/accounts/signup.html
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token%}
    {{ form }}
    <input type = "submit" value="Signup">
</form>

Django Girls/greetings/templates/greetings/create.html
<div class="create-article">
    <h2>Create an awesome greeting</h2>
</div>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

Django Girls/greetings/templates/greetings/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.message }}"?</p>
    <input type="submit" value="Confirm">
</form>

Django Girls/greetings/templates/greetings/examples.html
<h1>Some examples of greetings:</h1>
    <ul>
        <li>Salutations</li>
        <li>Hello, Zuko here</li>
        <li>Ahoy, matey</li>
        <li>Top of the mornin’ to ya!</li>
    </ul>
    <a href="{% url 'greetings:index' %}">Get back to the submit greetings page</a>

Django Girls/greetings/templates/greetings/index.html
<nav>
    <ul>
        <li>
            <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                {% csrf_token%}
                <button type="submit">Logout</button>
            </form>
        </li>
    </ul>
</nav>
<h1>Your greetings:</h1>
{% if greeting_list %}
    <ul type="square">
    {% for greeting in greeting_list %}
        <li>
          {{ greeting.message }}
          <span><a href="{% url 'greetings:update' greeting.id %}">edit</a></span>
          <span><a href="{% url 'greetings:delete' greeting.id %}">delete</a></span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No greetings are available.</p>
{% endif %}
<a href="{% url 'greetings:create' %}">Create a New Greeting</a>
<br>
<a href="{% url 'greetings:examples' %}">See some example greetings for inspiration</a>

Django Girls/greetings/templates/greetings/update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'greetings:delete' greeting.id %}">delete</a>
</form>

Django Girls/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Something</title>
    </head>
</html>